version: "3.7"

services:
    crawler1:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        working_dir: /var/www/
        container_name: crawler1
        extra_hosts:
            - "host.docker.internal:host-gateway"
        environment:
            - PHP_IDE_CONFIG=serverName=XdebugServer
        volumes:
            - ./:/var/www
        depends_on:
            - redis
        networks:
            - laravel

    crawler2:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        working_dir: /var/www/
        container_name: crawler2
        volumes:
            - ./:/var/www
        depends_on:
            - crawler1
            - redis
        networks:
            - laravel

    nginx:
        image: nginx:alpine
        container_name: nginx
        restart: unless-stopped
        ports:
            - "8990:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - laravel

    db:
        image: mysql:5.7.22
        restart: unless-stopped
        container_name: mysql-db
        environment:
            MYSQL_DATABASE: ${DB_DATABASE:-laravel}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
            MYSQL_PASSWORD: ${DB_PASSWORD:-userpass}
            MYSQL_USER: ${DB_USERNAME:-username}
        volumes:
            - ./.docker/mysql/dbdata:/var/lib/mysql
        ports:
            - "3390:3306"
        networks:
            - laravel

    redis:
        image: redis:latest
        container_name: redis
        networks:
            - laravel

networks:
    laravel:
        driver: bridge
